changelog:
  exclude:
    labels: [skip-changelog]
    authors: [dependabot, github-actions]
  categories:
    - title: New
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Docs
      labels: [documentation]
    - title: Other changes
      labels: ['*']
